### ISSUE TITLE
what is the expected normal memory usage?

### ISSUE THREAD

**Issue by hugalafutro** [mko-x/docker-clamav#91]
Hi,
the container is using 1.4GB memory, I can spare the ram, just wondering if this is expected memory usage.

Thanks.

**Comment by mko-x** [comment]
Hi @hugalafutro ,

there is no direct answer to your question. It depends on your operating system, available memory, used memory, configuration, clam version, what you are doing/scanning with clamav, Scanning emai, Periodic disk scans etc.

There are so many things with influence.

Memory consumption of clamav is high by design, as the databases have to be checked 100% for any scan. 

Freshclam peaks with memory if downloading databases as well (initial update).

**Comment by hugalafutro** [comment]
I use it as a scanner on a pretty much idle Nextcloud instance (only 1 user - myself) and the system it runs on has 12GB memory available, with 8GB Used.

Thanks for your explanation, I will not worry about the memory usage unless it starts nearing the max available ram or something like that which it doesn't seem likely to do as it pretty much sits at the same memory usage.

**Comment by mko-x** [comment]
You're welcome.

You could try to limit the memory usage of the container by args like
```
--memory=”[memory_limit]”
```

e.g.
```
$ docker run -d -p 3310:3310 --memory=”1g” mkodockx/docker-clamav:alpine
```

For detailed infos tty into the container and check by
```
$ clamdtop
```

**Comment by hugalafutro** [comment]
Seems the usage drops by itself. I was about to try the mem_limit, when I checked the container and it's using only ~500MB now. So it probably only uses that much on starting and updating.

Thanks again!

**Comment by sdellenb** [comment]
In my case, the most resource intensive part is the signature update, where I get daily warnings about memory running out on the container. 😉 

It still makes sense to limit Memory and CPU in case of archive bombs designed to trip the Antivirus program (and by extension the Docker host) into a DoS.
